-- Autocmd 会在 VeryLazy 事件时自动加载
-- 默认已设置的 autocmd：https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- 在这里添加额外的 autocmd
-- 使用 `vim.api.nvim_create_autocmd`
--
-- 或通过组名移除已有的 autocmd（默认组名前缀为 `lazyvim_`）
-- 例如：vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
